proxy:
  image: nginx:1.13.8
  container_name: nginx-proxy
  links:
    - comic-site:comic-site
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./comic_site/media:/media
    - ./comic_site/static:/static
  ports:
    - 8000:8000

comic-site:
  image: excorde314/comic-site:1.4
  container_name: comic-site
  external_links:
    -  mysql:db
  volumes:
    -  ./comic_site:/app
  environment:
    DJANGO_PRODUCTION: "development"
  ports:
    - 8080:8080
  command: bash -c "cp /app/fixtures/*.png /app/media &&
                    python manage.py makemigrations blog comic info admin --noinput &&
                    python manage.py migrate --noinput &&
                    python manage.py loaddata /app/fixtures/db.json &&
                    python manage.py loaddata /app/fixtures/test_fixtures.json &&
                    gunicorn --reload --bind 0.0.0.0:8080 comic_site.wsgi"

