comic-site:
    image: excorde314/comic-site:1.2
    container_name: comic-site
    external_links:
      -  mysql:db
    volumes:
      -  ./comic_site:/app
    ports:
      - 8000:8000
    command: bash -c "cp /app/fixtures/*.png /app/media &&
                      python manage.py makemigrations blog comic info admin --noinput &&
                      python manage.py migrate --noinput &&
                      python manage.py loaddata /app/fixtures/db.json &&
                      python manage.py loaddata /app/fixtures/test_fixtures.json &&
                      mod_wsgi-express start-server --url-alias /static /app/static
                                                    --url-alias /media /app/media
                                                    --working-directory /app
                                                    --reload-on-changes /app/comic_site/wsgi.py
                                                    --compress-responses
                                                    --include-file /app/additional_rules.conf"